spring.application.name=student-activity
server.port=8081

# H2 Console config
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./studentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Security Logging
logging.level.org.springframework.security=DEBUG
